// Generated by gencpp from file orb_slam2_ros/PoseGraphKeyFrame.msg
// DO NOT EDIT!


#ifndef ORB_SLAM2_ROS_MESSAGE_POSEGRAPHKEYFRAME_H
#define ORB_SLAM2_ROS_MESSAGE_POSEGRAPHKEYFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace orb_slam2_ros
{
template <class ContainerAllocator>
struct PoseGraphKeyFrame_
{
  typedef PoseGraphKeyFrame_<ContainerAllocator> Type;

  PoseGraphKeyFrame_()
    : header()
    , keyframe_id(0)
    , pose()
    , timestamp(0.0)  {
    }
  PoseGraphKeyFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , keyframe_id(0)
    , pose(_alloc)
    , timestamp(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _keyframe_id_type;
  _keyframe_id_type keyframe_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> const> ConstPtr;

}; // struct PoseGraphKeyFrame_

typedef ::orb_slam2_ros::PoseGraphKeyFrame_<std::allocator<void> > PoseGraphKeyFrame;

typedef boost::shared_ptr< ::orb_slam2_ros::PoseGraphKeyFrame > PoseGraphKeyFramePtr;
typedef boost::shared_ptr< ::orb_slam2_ros::PoseGraphKeyFrame const> PoseGraphKeyFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator1> & lhs, const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.keyframe_id == rhs.keyframe_id &&
    lhs.pose == rhs.pose &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator1> & lhs, const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace orb_slam2_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bd14b990739982b06eb1cfab09a2dfe";
  }

  static const char* value(const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bd14b990739982bULL;
  static const uint64_t static_value2 = 0x06eb1cfab09a2dfeULL;
};

template<class ContainerAllocator>
struct DataType< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orb_slam2_ros/PoseGraphKeyFrame";
  }

  static const char* value(const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 keyframe_id\n"
"geometry_msgs/Pose pose\n"
"float64 timestamp\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.keyframe_id);
      stream.next(m.pose);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseGraphKeyFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orb_slam2_ros::PoseGraphKeyFrame_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "keyframe_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.keyframe_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_ROS_MESSAGE_POSEGRAPHKEYFRAME_H
