; Auto-generated. Do not edit!


(cl:in-package graph_d_exploration-msg)


;//! \htmlinclude ChooseGoalFeedback.msg.html

(cl:defclass <ChooseGoalFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ChooseGoalFeedback (<ChooseGoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChooseGoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChooseGoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graph_d_exploration-msg:<ChooseGoalFeedback> is deprecated: use graph_d_exploration-msg:ChooseGoalFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <ChooseGoalFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graph_d_exploration-msg:status-val is deprecated.  Use graph_d_exploration-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChooseGoalFeedback>) ostream)
  "Serializes a message object of type '<ChooseGoalFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'status) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChooseGoalFeedback>) istream)
  "Deserializes a message object of type '<ChooseGoalFeedback>"
    (cl:setf (cl:slot-value msg 'status) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChooseGoalFeedback>)))
  "Returns string type for a message object of type '<ChooseGoalFeedback>"
  "graph_d_exploration/ChooseGoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChooseGoalFeedback)))
  "Returns string type for a message object of type 'ChooseGoalFeedback"
  "graph_d_exploration/ChooseGoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChooseGoalFeedback>)))
  "Returns md5sum for a message object of type '<ChooseGoalFeedback>"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChooseGoalFeedback)))
  "Returns md5sum for a message object of type 'ChooseGoalFeedback"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChooseGoalFeedback>)))
  "Returns full string definition for message of type '<ChooseGoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%# The feedback specifies how many goals have already been chosen~%bool status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChooseGoalFeedback)))
  "Returns full string definition for message of type 'ChooseGoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%# The feedback specifies how many goals have already been chosen~%bool status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChooseGoalFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChooseGoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ChooseGoalFeedback
    (cl:cons ':status (status msg))
))
