; Auto-generated. Do not edit!


(cl:in-package graph_d_exploration-msg)


;//! \htmlinclude ChooseGoalResult.msg.html

(cl:defclass <ChooseGoalResult> (roslisp-msg-protocol:ros-message)
  ((goals
    :reader goals
    :initarg :goals
    :type (cl:vector graph_d_exploration-msg:Point2D)
   :initform (cl:make-array 0 :element-type 'graph_d_exploration-msg:Point2D :initial-element (cl:make-instance 'graph_d_exploration-msg:Point2D))))
)

(cl:defclass ChooseGoalResult (<ChooseGoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChooseGoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChooseGoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graph_d_exploration-msg:<ChooseGoalResult> is deprecated: use graph_d_exploration-msg:ChooseGoalResult instead.")))

(cl:ensure-generic-function 'goals-val :lambda-list '(m))
(cl:defmethod goals-val ((m <ChooseGoalResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graph_d_exploration-msg:goals-val is deprecated.  Use graph_d_exploration-msg:goals instead.")
  (goals m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChooseGoalResult>) ostream)
  "Serializes a message object of type '<ChooseGoalResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'goals))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'goals))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChooseGoalResult>) istream)
  "Deserializes a message object of type '<ChooseGoalResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'goals) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'goals)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'graph_d_exploration-msg:Point2D))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChooseGoalResult>)))
  "Returns string type for a message object of type '<ChooseGoalResult>"
  "graph_d_exploration/ChooseGoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChooseGoalResult)))
  "Returns string type for a message object of type 'ChooseGoalResult"
  "graph_d_exploration/ChooseGoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChooseGoalResult>)))
  "Returns md5sum for a message object of type '<ChooseGoalResult>"
  "a2c21c3b8a704248b81012ec176525a6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChooseGoalResult)))
  "Returns md5sum for a message object of type 'ChooseGoalResult"
  "a2c21c3b8a704248b81012ec176525a6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChooseGoalResult>)))
  "Returns full string definition for message of type '<ChooseGoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%# The result specifies the chosen points for each agent~%Point2D[] goals~%~%================================================================================~%MSG: graph_d_exploration/Point2D~%# Point for centroids~%float32 x~%float32 y~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChooseGoalResult)))
  "Returns full string definition for message of type 'ChooseGoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%# The result specifies the chosen points for each agent~%Point2D[] goals~%~%================================================================================~%MSG: graph_d_exploration/Point2D~%# Point for centroids~%float32 x~%float32 y~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChooseGoalResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'goals) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChooseGoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ChooseGoalResult
    (cl:cons ':goals (goals msg))
))
