; Auto-generated. Do not edit!


(cl:in-package graph_d_exploration-msg)


;//! \htmlinclude MergePointsFeedback.msg.html

(cl:defclass <MergePointsFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_completed
    :reader percent_completed
    :initarg :percent_completed
    :type cl:float
    :initform 0.0))
)

(cl:defclass MergePointsFeedback (<MergePointsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MergePointsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MergePointsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name graph_d_exploration-msg:<MergePointsFeedback> is deprecated: use graph_d_exploration-msg:MergePointsFeedback instead.")))

(cl:ensure-generic-function 'percent_completed-val :lambda-list '(m))
(cl:defmethod percent_completed-val ((m <MergePointsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader graph_d_exploration-msg:percent_completed-val is deprecated.  Use graph_d_exploration-msg:percent_completed instead.")
  (percent_completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MergePointsFeedback>) ostream)
  "Serializes a message object of type '<MergePointsFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_completed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MergePointsFeedback>) istream)
  "Deserializes a message object of type '<MergePointsFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_completed) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MergePointsFeedback>)))
  "Returns string type for a message object of type '<MergePointsFeedback>"
  "graph_d_exploration/MergePointsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MergePointsFeedback)))
  "Returns string type for a message object of type 'MergePointsFeedback"
  "graph_d_exploration/MergePointsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MergePointsFeedback>)))
  "Returns md5sum for a message object of type '<MergePointsFeedback>"
  "2cfbe45a73922160426e29b7a5f151e0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MergePointsFeedback)))
  "Returns md5sum for a message object of type 'MergePointsFeedback"
  "2cfbe45a73922160426e29b7a5f151e0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MergePointsFeedback>)))
  "Returns full string definition for message of type '<MergePointsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the action feedback message~%float32 percent_completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MergePointsFeedback)))
  "Returns full string definition for message of type 'MergePointsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the action feedback message~%float32 percent_completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MergePointsFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MergePointsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MergePointsFeedback
    (cl:cons ':percent_completed (percent_completed msg))
))
