# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from graph_d_exploration/MergePointsResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import graph_d_exploration.msg

class MergePointsResult(genpy.Message):
  _md5sum = "5567672ae4c3263cec809b91db7a6653"
  _type = "graph_d_exploration/MergePointsResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Define the action result message
Point2D[] merged_points
float32 radius_used
float32 percentage_used

================================================================================
MSG: graph_d_exploration/Point2D
# Point for centroids
float32 x
float32 y"""
  __slots__ = ['merged_points','radius_used','percentage_used']
  _slot_types = ['graph_d_exploration/Point2D[]','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       merged_points,radius_used,percentage_used

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MergePointsResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.merged_points is None:
        self.merged_points = []
      if self.radius_used is None:
        self.radius_used = 0.
      if self.percentage_used is None:
        self.percentage_used = 0.
    else:
      self.merged_points = []
      self.radius_used = 0.
      self.percentage_used = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.merged_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.merged_points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      _x = self
      buff.write(_get_struct_2f().pack(_x.radius_used, _x.percentage_used))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.merged_points is None:
        self.merged_points = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.merged_points = []
      for i in range(0, length):
        val1 = graph_d_exploration.msg.Point2D()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.merged_points.append(val1)
      _x = self
      start = end
      end += 8
      (_x.radius_used, _x.percentage_used,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.merged_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.merged_points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      _x = self
      buff.write(_get_struct_2f().pack(_x.radius_used, _x.percentage_used))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.merged_points is None:
        self.merged_points = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.merged_points = []
      for i in range(0, length):
        val1 = graph_d_exploration.msg.Point2D()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.merged_points.append(val1)
      _x = self
      start = end
      end += 8
      (_x.radius_used, _x.percentage_used,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
