// Generated by gencpp from file graph_d_exploration/BoolArray.msg
// DO NOT EDIT!


#ifndef GRAPH_D_EXPLORATION_MESSAGE_BOOLARRAY_H
#define GRAPH_D_EXPLORATION_MESSAGE_BOOLARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_d_exploration
{
template <class ContainerAllocator>
struct BoolArray_
{
  typedef BoolArray_<ContainerAllocator> Type;

  BoolArray_()
    : availability()  {
    }
  BoolArray_(const ContainerAllocator& _alloc)
    : availability(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _availability_type;
  _availability_type availability;





  typedef boost::shared_ptr< ::graph_d_exploration::BoolArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_d_exploration::BoolArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoolArray_

typedef ::graph_d_exploration::BoolArray_<std::allocator<void> > BoolArray;

typedef boost::shared_ptr< ::graph_d_exploration::BoolArray > BoolArrayPtr;
typedef boost::shared_ptr< ::graph_d_exploration::BoolArray const> BoolArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_d_exploration::BoolArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_d_exploration::BoolArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_d_exploration::BoolArray_<ContainerAllocator1> & lhs, const ::graph_d_exploration::BoolArray_<ContainerAllocator2> & rhs)
{
  return lhs.availability == rhs.availability;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_d_exploration::BoolArray_<ContainerAllocator1> & lhs, const ::graph_d_exploration::BoolArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_d_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::BoolArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::BoolArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::BoolArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31080b5ad54e6a85d10a027f73e819fc";
  }

  static const char* value(const ::graph_d_exploration::BoolArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31080b5ad54e6a85ULL;
  static const uint64_t static_value2 = 0xd10a027f73e819fcULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_d_exploration/BoolArray";
  }

  static const char* value(const ::graph_d_exploration::BoolArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Arrays of booleans\n"
"bool[] availability\n"
;
  }

  static const char* value(const ::graph_d_exploration::BoolArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.availability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_d_exploration::BoolArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_d_exploration::BoolArray_<ContainerAllocator>& v)
  {
    s << indent << "availability[]" << std::endl;
    for (size_t i = 0; i < v.availability.size(); ++i)
    {
      s << indent << "  availability[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.availability[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_D_EXPLORATION_MESSAGE_BOOLARRAY_H
