// Generated by gencpp from file graph_d_exploration/ChooseGoalResult.msg
// DO NOT EDIT!


#ifndef GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALRESULT_H
#define GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <graph_d_exploration/Point2D.h>

namespace graph_d_exploration
{
template <class ContainerAllocator>
struct ChooseGoalResult_
{
  typedef ChooseGoalResult_<ContainerAllocator> Type;

  ChooseGoalResult_()
    : goals()  {
    }
  ChooseGoalResult_(const ContainerAllocator& _alloc)
    : goals(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::graph_d_exploration::Point2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::graph_d_exploration::Point2D_<ContainerAllocator> >> _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> const> ConstPtr;

}; // struct ChooseGoalResult_

typedef ::graph_d_exploration::ChooseGoalResult_<std::allocator<void> > ChooseGoalResult;

typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalResult > ChooseGoalResultPtr;
typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalResult const> ChooseGoalResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator1> & lhs, const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator2> & rhs)
{
  return lhs.goals == rhs.goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator1> & lhs, const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_d_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2c21c3b8a704248b81012ec176525a6";
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2c21c3b8a704248ULL;
  static const uint64_t static_value2 = 0xb81012ec176525a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_d_exploration/ChooseGoalResult";
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result definition\n"
"# The result specifies the chosen points for each agent\n"
"Point2D[] goals\n"
"\n"
"================================================================================\n"
"MSG: graph_d_exploration/Point2D\n"
"# Point for centroids\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChooseGoalResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_d_exploration::ChooseGoalResult_<ContainerAllocator>& v)
  {
    s << indent << "goals[]" << std::endl;
    for (size_t i = 0; i < v.goals.size(); ++i)
    {
      s << indent << "  goals[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::graph_d_exploration::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.goals[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALRESULT_H
