// Generated by gencpp from file graph_d_exploration/ChooseGoalFeedback.msg
// DO NOT EDIT!


#ifndef GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALFEEDBACK_H
#define GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_d_exploration
{
template <class ContainerAllocator>
struct ChooseGoalFeedback_
{
  typedef ChooseGoalFeedback_<ContainerAllocator> Type;

  ChooseGoalFeedback_()
    : status(false)  {
    }
  ChooseGoalFeedback_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ChooseGoalFeedback_

typedef ::graph_d_exploration::ChooseGoalFeedback_<std::allocator<void> > ChooseGoalFeedback;

typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalFeedback > ChooseGoalFeedbackPtr;
typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalFeedback const> ChooseGoalFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator1> & lhs, const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator1> & lhs, const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_d_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_d_exploration/ChooseGoalFeedback";
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback definition\n"
"# The feedback specifies how many goals have already been chosen\n"
"bool status\n"
"\n"
;
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChooseGoalFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_d_exploration::ChooseGoalFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALFEEDBACK_H
