// Generated by gencpp from file graph_d_exploration/ChooseGoalActionGoal.msg
// DO NOT EDIT!


#ifndef GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALACTIONGOAL_H
#define GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <graph_d_exploration/ChooseGoalGoal.h>

namespace graph_d_exploration
{
template <class ContainerAllocator>
struct ChooseGoalActionGoal_
{
  typedef ChooseGoalActionGoal_<ContainerAllocator> Type;

  ChooseGoalActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ChooseGoalActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::graph_d_exploration::ChooseGoalGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ChooseGoalActionGoal_

typedef ::graph_d_exploration::ChooseGoalActionGoal_<std::allocator<void> > ChooseGoalActionGoal;

typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalActionGoal > ChooseGoalActionGoalPtr;
typedef boost::shared_ptr< ::graph_d_exploration::ChooseGoalActionGoal const> ChooseGoalActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator1> & lhs, const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator1> & lhs, const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_d_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a3a439f8bebc3ea8ec8e111f7acaf9a";
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a3a439f8bebc3eaULL;
  static const uint64_t static_value2 = 0x8ec8e111f7acaf9aULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_d_exploration/ChooseGoalActionGoal";
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ChooseGoalGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: graph_d_exploration/ChooseGoalGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Action definition for choosing centroids\n"
"# The goal specifies the client id and the matrix with the lists in which each element is of the form [Reward, X, Y]\n"
"# The action server should try to choose the centroid that maximizes the information gain depending on the priority\n"
"# of the robots (r0 > ... > rn)\n"
"\n"
"# Goal definition\n"
"string client_id\n"
"InfoMatrix matrix\n"
"int8 rows\n"
"string robot_id\n"
"\n"
"================================================================================\n"
"MSG: graph_d_exploration/InfoMatrix\n"
"# Matrix of type [Reward, X, Y] with dimensions [nx3]\n"
"uint32 rows\n"
"float32[] data\n"
;
  }

  static const char* value(const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChooseGoalActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_d_exploration::ChooseGoalActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::graph_d_exploration::ChooseGoalGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_D_EXPLORATION_MESSAGE_CHOOSEGOALACTIONGOAL_H
