// Generated by gencpp from file graph_d_exploration/MergePointsResult.msg
// DO NOT EDIT!


#ifndef GRAPH_D_EXPLORATION_MESSAGE_MERGEPOINTSRESULT_H
#define GRAPH_D_EXPLORATION_MESSAGE_MERGEPOINTSRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <graph_d_exploration/Point2D.h>

namespace graph_d_exploration
{
template <class ContainerAllocator>
struct MergePointsResult_
{
  typedef MergePointsResult_<ContainerAllocator> Type;

  MergePointsResult_()
    : merged_points()
    , radius_used(0.0)
    , percentage_used(0.0)  {
    }
  MergePointsResult_(const ContainerAllocator& _alloc)
    : merged_points(_alloc)
    , radius_used(0.0)
    , percentage_used(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::graph_d_exploration::Point2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::graph_d_exploration::Point2D_<ContainerAllocator> >> _merged_points_type;
  _merged_points_type merged_points;

   typedef float _radius_used_type;
  _radius_used_type radius_used;

   typedef float _percentage_used_type;
  _percentage_used_type percentage_used;





  typedef boost::shared_ptr< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> const> ConstPtr;

}; // struct MergePointsResult_

typedef ::graph_d_exploration::MergePointsResult_<std::allocator<void> > MergePointsResult;

typedef boost::shared_ptr< ::graph_d_exploration::MergePointsResult > MergePointsResultPtr;
typedef boost::shared_ptr< ::graph_d_exploration::MergePointsResult const> MergePointsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_d_exploration::MergePointsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_d_exploration::MergePointsResult_<ContainerAllocator1> & lhs, const ::graph_d_exploration::MergePointsResult_<ContainerAllocator2> & rhs)
{
  return lhs.merged_points == rhs.merged_points &&
    lhs.radius_used == rhs.radius_used &&
    lhs.percentage_used == rhs.percentage_used;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_d_exploration::MergePointsResult_<ContainerAllocator1> & lhs, const ::graph_d_exploration::MergePointsResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_d_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5567672ae4c3263cec809b91db7a6653";
  }

  static const char* value(const ::graph_d_exploration::MergePointsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5567672ae4c3263cULL;
  static const uint64_t static_value2 = 0xec809b91db7a6653ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_d_exploration/MergePointsResult";
  }

  static const char* value(const ::graph_d_exploration::MergePointsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the action result message\n"
"Point2D[] merged_points\n"
"float32 radius_used\n"
"float32 percentage_used\n"
"\n"
"================================================================================\n"
"MSG: graph_d_exploration/Point2D\n"
"# Point for centroids\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::graph_d_exploration::MergePointsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.merged_points);
      stream.next(m.radius_used);
      stream.next(m.percentage_used);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MergePointsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_d_exploration::MergePointsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_d_exploration::MergePointsResult_<ContainerAllocator>& v)
  {
    s << indent << "merged_points[]" << std::endl;
    for (size_t i = 0; i < v.merged_points.size(); ++i)
    {
      s << indent << "  merged_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::graph_d_exploration::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.merged_points[i]);
    }
    s << indent << "radius_used: ";
    Printer<float>::stream(s, indent + "  ", v.radius_used);
    s << indent << "percentage_used: ";
    Printer<float>::stream(s, indent + "  ", v.percentage_used);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_D_EXPLORATION_MESSAGE_MERGEPOINTSRESULT_H
